"""Regenerate the model tables in README.md / README_zh.md from weatherpre/catalog.py.
    python scripts/gen_model_table.py            # rewrites the block between <!-- MODELS:START --> and <!-- MODELS:END -->"""
import pathlib, re, sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
from weatherpre import catalog as C

STATUS = {"hosted": "✅ hosted", "gpu": "🟡 GPU", "blocked": "⛔"}

def rows(scale):
    out = ["| Model | Type | Status | Route | Grid | Lead | Hosted period | Licence |", "|---|---|---|---|---|---|---|---|"]
    ms = sorted(C.for_scale(scale), key=lambda m: ({"hosted": 0, "gpu": 1, "blocked": 2}[m.status], m.kind == "baseline"))
    for m in ms:
        name = f"[`{m.name}`]({m.ref})" if m.ref else f"`{m.name}`"
        route = ", ".join(r if r != "e2s" else f"Earth2Studio `{m.e2s}`" for r in m.routes) or "–"
        out.append(f"| {name} {m.label} | {m.kind} | {STATUS[m.status]} | {route} | {m.grid} | {m.lead} | {m.period} | {m.licence} |")
    return "\n".join(out)

def block():
    return ("<!-- MODELS:START (generated by scripts/gen_model_table.py, do not edit) -->\n"
            f"**Weather scale (≤ 15 days)**\n\n{rows(C.WEATHER)}\n\n**S2S scale (> 15 days, weekly means)**\n\n{rows(C.S2S)}\n"
            "<!-- MODELS:END -->")

if __name__ == "__main__":
    for f in ("README.md", "README_zh.md"):
        p = pathlib.Path(f)
        if not p.exists(): continue
        s = p.read_text()
        s2 = re.sub(r"<!-- MODELS:START.*?<!-- MODELS:END -->", lambda _: block(), s, flags=re.S)
        p.write_text(s2); print("updated", f, "(changed)" if s2 != s else "(unchanged)")
